version: "3.9"

services:
  backend:
    build:
      context: ./backend
    env_file:
      - ./backend/.env
    ports:
      - "3001:3001"
    depends_on:
      - db
      - redis

  frontend:
    build:
      context: ./frontend
    env_file:
      - ./frontend/.env.local
    ports:
      - "3000:3000"
    depends_on:
      - backend

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: argus
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: argus
    volumes:
      - ./data/db:/var/lib/postgresql/data

  redis:
    image: redis:7
    command: redis-server --appendonly yes
    volumes:
      - ./data/redis:/data

  nginx:
    image: nginx:latest
    volumes:
      - ./deploy/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./deploy/certs:/etc/ssl/certs:ro
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - frontend
